language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
notifications:
  slack:
    secure: nXhFZW/4NNGkc1WUpwn2YqEEtoACiwYHUkv6p5CTUGV+HWvlBFKgtskeM3rdJ6GYuSq1W69enmT1Pv09s2mqIU1gkfPkMxzHwCu+XUq68pnM32mxpDGxchhHNIq4PDApNA9kLklYeKXRYAKKNWcthJdCdnNoeBodEDue6AM5wwnsewEfqilu7Ozb7yI7+9wkcdG7TnGrrlsrR1sVdrlLdatqcxt02tfCWBOLV4m0WZerqZBTlMhsCXd/Sn8CwHxKhwaa7F3c8LytUk1OLOQpVtAF9GL1IljgpGC/HCXP/SZ87ZJpJoQRqUEjfzwv95saf+C7lYmYdO3j9uovRlFViR0HMBDdqXpOan8K2CYyDMjOYwh/04uzzGLpRBxi/Z/W7KLRAJvSZyQNHGbEMi/Ztw+kaWmZQGD2bT0Lzki7UCQdo0jDfmYiAS6KiFsvY54jsXNNxC6+QUfaDCos09GAzERxeIUsF7bPlAY1fwpO42E3AhMmghh/UMy5TjFADBootlP2RnqF1fw3T5J69ulW6OmyGL4i7jgQ0DYZOmpbOhc1UcTvJsaz1HQ9l0P5ye6oJadRmEtY2jHZHplBI3SFqzy/Y6sFjfMxxU0J7gZsOktn5ZzYY7CsnsDS4v1Om+KjSMnbCJCtgR8DM4dn3JLtQKt8H6eS0d+k4ENigqZ4H2Q=
