# PvP Storm's Configuration File

start-message: A PvP Storm approaches the PvP Arena!
end-message: The skies clear and the world returns to normal.
stormer-host: Jflory7

death-prizes:
participation-prizes:
