name: PvPStorm
main: com.crystalcraftmc.pvpstorm.PvPStorm
version: 0.0.2
description: Make your players fight the powers of the gods!
authors: [jflory7, Jacc734, Jwood9198]
website: https://github.com/CrystalCraftMC/PvPStorm

commands:
    storm:
        description: Get more information about using the plugin.
        usage: /storm <start|stop|power>
        permisson: pvpstorm.storm
        permission-message: You do not have permission to use <permission>.
        aliases: [pvpstorm, ps]
        
permissions:
    pvpstorm.storm:
        description: Get more information about using the plugin.
        default: op