name: PvP Storm
main: com.crystalcraftmc.pvpstorm.PvPStorm
version: 0.0.1
description: Make your players fight the powers of the gods!
authors: [jflory7, Jacc734, Jwood9198]
website: http://crystalcraftmc.com